name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: |
        cd LevelUp.Services.Core
        dotnet build --configuration Release --no-restore
        
    - name: Test
      run: |
        cd LevelUp.Services.Tests
        dotnet test --no-restore --verbosity normal

    - name: Deploy
      run: | 
        dotnet pack --configuration Release --output ./release
        cd ./release
        nuget push **\*.nupkg -Source 'https://github.com/LevelUpSoftware/index.json -ApiKey ${{secrets.NUGET_PUBLISH}}
        
